//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENCUESTA.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public long resultadosid { get; set; }
        public long usuarioid { get; set; }
        public string resultadototal { get; set; }
        public System.DateTime fecharesultado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
